language: objective-c
osx_image: beta-xcode6.3
xcode_project: ParkenDD.xcodeproj
xcode_scheme: ParkenDD

notifications:
  email: false

before_install:
  - brew update
  - brew install carthage
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - carthage bootstrap

script: xctool -workspace ParkenDD.xcworkspace -scheme ParkenDD build test -sdk iphonesimulator
